---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: api
  name: ingress-nginx-developer-root
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  #  nginx.ingress.kubernetes.io/proxy-redirect-from: default
  #  nginx.ingress.kubernetes.io/proxy-redirect-to: "ok.com"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-WSO2-Tenant "carbon.super";
#        proxy_read_timeout 5m;
#        proxy_send_timeout 5m;
spec:
  tls:
  - secretName: tls-cert
    hosts:
    - developer.internal.bhn.technology
  rules:
    - host: developer.internal.bhn.technology
      http:
        paths:        
        - path: /
          pathType: Prefix
          backend:
            service:
              name: apistudio
              port:
                number: 9443

---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: api
  name: ingress-nginx-developer-oauth
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-WSO2-Tenant "carbon.super";
#        proxy_read_timeout 5m;
#        proxy_send_timeout 5m;
spec:
  #ingressClassName: nginx
  tls:
  - secretName: tls-cert
    hosts:
    - developer.internal.bhn.technology
  rules:
    - host: developer.internal.bhn.technology
      http:
        paths:        
        - path: /oauth2
          pathType: Prefix
          backend:
            service:
              name: apistudio
              port:
                number: 9443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: api
  name: ingress-nginx-developer-allauth
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-redirect-from: https://developer.internal.bhn.technology/devportal/
    nginx.ingress.kubernetes.io/proxy-redirect-to: https://developer.internal.bhn.technology/
#    nginx.ingress.kubernetes.io/server-snippet: |
#      location / {
#          proxy_set_header X-Forwarded-Host $host;
#          proxy_set_header X-Forwarded-Server $host;
#          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#          proxy_set_header Host $http_host;
#          proxy_read_timeout 5m;
#          proxy_send_timeout 5m;
#          proxy_pass https://192.168.1.8:9443/devportal/;
#          proxy_redirect https://192.168.1.8:9443/devportal/ /;
#          proxy_set_header X-WSO2-Tenant "wso2.com";
#      }
#      location ~ (/api/am/devportal/v2|/authenticationendpoint|/logincontext|/commonauth|/oidc) {
#           proxy_set_header X-Forwarded-Host $host;
#           proxy_set_header X-Forwarded-Server $host;
#           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#           proxy_set_header Host $http_host;
#           proxy_read_timeout 5m;
#           proxy_send_timeout 5m;
#           proxy_pass https://192.168.1.8:9443;
#           proxy_set_header X-WSO2-Tenant "wso2.com";
#    }       
#    location ~ (/oauth2) {
#           proxy_set_header X-Forwarded-Host $host;
#           proxy_set_header X-Forwarded-Server $host;
#           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#           proxy_set_header Host $http_host;
#           proxy_read_timeout 5m;
#           proxy_send_timeout 5m;
#           proxy_pass https://192.168.1.8:9443;
#           proxy_redirect https://192.168.1.8:9443/ https://developer.wso2.com/;
#           proxy_set_header X-WSO2-Tenant "wso2.com";
#    }
    nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-WSO2-Tenant "carbon.super";
 #      proxy_read_timeout 5m;
#       proxy_send_timeout 5m;
spec:
  #ingressClassName: nginx
  tls:
  - secretName: tls-cert
    hosts:
    - developer.internal.bhn.technology
  rules:
    - host: developer.internal.bhn.technology
      http:
        paths:        
        - path: /api/am/devportal/v2
          pathType: Prefix
          backend:
            service:
              name: apistudio
              port:
                number: 9443
        - path: /authenticationendpoint
          pathType: Prefix
          backend:
            service:
              name: apistudio
              port:
                number: 9443
        - path: /logincontext
          pathType: Prefix
          backend:
            service:
              name: apistudio
              port:
                number: 9443
        - path: /commonauth
          pathType: Prefix
          backend:
            service:
              name: apistudio
              port:
                number: 9443                                
        - path: /oidc
          pathType: Prefix
          backend:
            service:
              name: apistudio
              port:
                number: 9443    
---
#apiVersion: k8s.nginx.org/v1
#kind: VirtualServer
#metadata:
#  namespace: api
#  name: ingress-nginx-developer
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
#spec:
#  host: developer.internal.bhn.technology
#  tls:
#    secret: tls-cert
#  upstreams:
#    - name: apistudio
#      service: apistudio
#      port: 9443
#  routes:
#  - path: /
#    location-snippets: |
#      proxy_redirect https://developer.internal.bhn.technology/devportal/ /;
#    action:
#     proxy:
#        upstream: apistudio
#        rewritePath: /devportal