version: '3'

volumes:
  postgre_shared:
  postgre_api:

services:
  shared-db:
    image: 'postgres:12.9'  
    ports:
      - 5432:5432 
    environment:
      POSTGRES_DB: shared
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: [ "CMD-SHELL", "PGPASSWORD=$${POSTGRES_PASSWORD} echo pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]

      #test: pg_isready -U pguser
    volumes:
      - 'postgre_shared:/var/lib/postgresql/data'
  api-db:
    image: 'postgres:12.9'  
    ports:
      - 6432:5432 
    healthcheck:
      test: [ "CMD-SHELL", "PGPASSWORD=$${POSTGRES_PASSWORD} echo pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      #test: pg_isready -U pguser
    environment:
      POSTGRES_DB: apimgmt
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - 'postgre_api:/var/lib/postgresql/data'
