apiVersion: v1
kind: Namespace
metadata:
  name: api
  labels:
    cert-manager-tls: kubed  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    com.bhn.service: apistudio
  name: apistudio
  namespace: api
spec:
  ports:
    - name: "admin"
      port: 9443
      targetPort: 9443
    - name: "nio"
      port: 8280
      targetPort: 8280
    - name: "nio-secure"
      port: 8243
      targetPort: 8243
  selector:
    com.bhn.service: apistudio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    com.bhn.service: apistudio
  name: apistudio
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      com.bhn.service: apistudio
  strategy: {}
  template:
    metadata:
      labels:
        com.bhn.service: apistudio
    spec:
      containers:
        - env:
            - name: PLACEHOLDER
              value: "true"
          image: 982306614752.dkr.ecr.us-west-2.amazonaws.com/wso2-apim:latest
          name: apistudio
          ports:
            - containerPort: 9443
            - containerPort: 8280
            - containerPort: 8243
          resources: {}
          volumeMounts:
            - name: keycloak-keystore
              readOnly: true
              mountPath: /home/wso2carbon/wso2-config-volume/keycloak.crt
              subPath: keycloak.crt
          envFrom:
            - configMapRef:
                name: env-bindings-cm
      volumes:
        - name: keycloak-keystore
          secret:
            secretName: keycloak-keystore
            items:
              - key: keycloak.crt
                path: keycloak.crt
            defaultMode: 420  
      restartPolicy: Always
status: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: api
  name: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" 
spec:
  #ingressClassName: nginx
  tls:
  - secretName: tls-cert
    hosts:
    - apigw.bhn.technology
    - apistudio.bhn.technology
  rules:
    - host: apistudio.bhn.technology
      http:
        paths:        
        - path: /
          pathType: Prefix
          backend:
            service:
              name: apistudio
              port:
                number: 9443
    - host: apigw.bhn.technology
      http:
        paths:        
        - path: /
          pathType: Prefix
          backend:
            service:
              name: apistudio
              port:
                number: 8243
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: api
  name: ingress-nginx-developer-devportal
  labels:
    app.kubernetes.io/name: ingress-nginx-developer
    app.kubernetes.io/part-of: ingress-nginx-developer
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #nginx.ingress.kubernetes.io/app-root: /devportal/
    nginx.ingress.kubernetes.io/proxy-cookie-path: '/ "/; SameSite=None"'
#   nginx.ingress.kubernetes.io/configuration-snippet: |
#      proxy_cookie_path / "/; SameSite=None";

spec:
  tls:
  - secretName: tls-cert
    hosts:
    - developer.internal.bhn.technology
  rules:
    - host: developer.internal.bhn.technology
      http:
        paths:
        - path: /devportal/
          pathType: Prefix
          backend:
            service:
              name: apistudio
              port:
                number: 9443
        - path: /
          pathType: Prefix
          backend:
            service:
              name: apistudio
              port:
                number: 9443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: api
  name: ingress-nginx-developer
  labels:
    app.kubernetes.io/name: ingress-nginx-developer
    app.kubernetes.io/part-of: ingress-nginx-developer
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #nginx.ingress.kubernetes.io/app-root: /devportal/
    nginx.ingress.kubernetes.io/rewrite-target: /devportal/$1
    nginx.ingress.kubernetes.io/proxy-cookie-path: '/ "/; SameSite=None"'
#   nginx.ingress.kubernetes.io/configuration-snippet: |
#      proxy_cookie_path / "/; SameSite=None";

spec:
  tls:
  - secretName: tls-cert
    hosts:
    - developer.internal.bhn.technology
  rules:
    - host: developer.internal.bhn.technology
      http:
        paths:
        - path: /(?!devportal|api|authenticationendpoint|logincontext|commonauth|oidc)(.*)
          pathType: Prefix
          backend:
            service:
              name: apistudio
              port:
                number: 9443
        - path: /(site)
          pathType: Prefix
          backend:
            service:
              name: apistudio
              port:
                number: 9443


---
#apiVersion: k8s.nginx.org/v1
#kind: VirtualServer
#metadata:
#  namespace: api
#  name: ingress-nginx-developer
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
#spec:
#  host: developer.internal.bhn.technology
#  tls:
#    secret: tls-cert
#  upstreams:
#    - name: apistudio
#      service: apistudio
#      port: 9443
#  routes:
#  - path: /
#    location-snippets: |
#      proxy_redirect https://developer.internal.bhn.technology/devportal/ /;
#    action:
#     proxy:
#        upstream: apistudio
#        rewritePath: /devportal